### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by emmannaemeka** [maedat/GFF2MSS#11]
Processing CBS11016_chr1A
Traceback (most recent call last):
File "GFF2MSS.py", line 161, in 
product_name = DF_Extract(anno_in, mRNA_ID)
File "GFF2MSS.py", line 31, in DF_Extract
out_DATA= tmp_DF.iat[0,1]
File "/Users/emmannadi/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 2200, in getitem
return self.obj._get_value(*key, takeable=self._takeable)
File "/Users/emmannadi/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2826, in _get_value
return com.maybe_box_datetimelike(series._values[index])
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by kfuku52** [comment]
I came across the same error today. This seems to be an error caused by the mismatch of gene names between `--gff` and `--ann`. The error disappeared when I changed the gene names in `--ann` to match gff's ID attributes of the "mRNA" features rather than the "gene" features.
